name: A workflow to build an application

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build the app
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c release --no-restore

    - name: Compress
      run: Compress-Archive -Path bin\Release\net6.0\* Release.zip

    - name: Generate release tag
      id: tag
      run: |
        $Tag = Get-Date -Format "yyy./MM.dd_HH:mm"
        echo "::set-output name=release_tag::$("$Tag")"

    - name: Get Previous tag
        id: previous_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.1.0

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{steps.previous_tag.outputs.tag}}
        files: Release.zip