name: A workflow to build an application

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build the app
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c release --no-restore

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        # Artifact name
        name: Release #.zip will be added automatically
        path: bin/Release/net6.0/